[project]
name = "federation-manager-rally"
version = "0.1.0"
description = ""
authors = [
    {name = "Alessandra Casale"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "rally-openstack (>=3.0.0,<4.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
